### ISSUE TITLE
Segmentation fault in libc __strlen_avx2 at startup with ProFTPD v1.3.7rc4

### ISSUE THREAD

**Issue by eomanis** [proftpd/proftpd#1042]
### What I Did

Built and ran [ProFTPD v1.3.7rc4](https://github.com/proftpd/proftpd/releases/tag/v1.3.7rc4) on Arch Linux, with a PKGBUILD derived from the `proftpd-2:1.3.6d-1` [AUR package](https://aur.archlinux.org/packages/proftpd/)

### What I Expected/Wanted

ProFTPD starts up and gets ready to serve connections

### What happened instead

ProFTPD immediately terminates with a segmentation fault

```
[root@mysystem ~]# /usr/bin/proftpd --nodaemon --config /etc/proftpd/proftpd.conf
2020-06-25 09:02:38,653 mysystem proftpd[750229]: -----BEGIN STACK TRACE-----
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [0] /usr/lib/libc.so.6(+0x1624b5) [0x7f01084734b5]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [1] /usr/lib/libc.so.6(+0x1624b5) [0x7f01084734b5]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [2] /usr/bin/proftpd(pstrcat+0x81) [0x556411781791]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [3] /usr/bin/proftpd(+0xdb963) [0x556411828963]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [4] /usr/bin/proftpd(pr_module_load+0x8b) [0x5564117a8d8b]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [5] /usr/bin/proftpd(modules_init+0x28) [0x5564117a9098]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [6] /usr/bin/proftpd(main+0x348) [0x55641177a588]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [7] /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7f0108338002]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: [8] /usr/bin/proftpd(_start+0x2e) [0x55641177adce]
2020-06-25 09:02:38,654 mysystem proftpd[750229]: -----END STACK TRACE-----
2020-06-25 09:02:38,654 mysystem proftpd[750229]: ProFTPD terminating (signal 11)
2020-06-25 09:02:38,654 mysystem proftpd[750229]: ProFTPD terminating (signal 11)
2020-06-25 09:02:38,655 mysystem proftpd[750229]: ProFTPD 1.3.7rc4 standalone mode SHUTDOWN
```

```
[root@mysystem ~]# gdb --args /usr/bin/proftpd --nodaemon --config /etc/proftpd/proftpd.conf
GNU gdb (GDB) 9.2
(...)
Reading symbols from /usr/bin/proftpd...
(No debugging symbols found in /usr/bin/proftpd)
(gdb) run
Starting program: /usr/bin/proftpd --nodaemon --config /etc/proftpd/proftpd.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff79cc4b5 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff79cc4b5 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x0000555555588791 in pstrcat ()
#2  0x000055555562f963 in ?? ()
#3  0x00005555555afd8b in pr_module_load ()
#4  0x00005555555b0098 in modules_init ()
#5  0x0000555555581588 in main ()
(gdb) quit 
(...)
```

The CPU is AVX2-capable ("avx2" is listed in the "flags" list in `/proc/cpuinfo`).

### ProFTPD Version and Configuration

```
[root@mysystem ~]# proftpd -V
Compile-time Settings:
  Version: 1.3.7rc4 (devel)
  Platform: LINUX [Linux 5.4.47-1-lts x86_64]
  Built: Do Jun 25 2020 08:57:53 CEST
  Built With:
    configure  '--prefix=/usr' '--sbindir=/usr/bin' '--libexecdir=/usr/lib' '--disable-pam' '--with-modules=mod_sftp:mod_quotatab:mod_quotatab_sql:mod_quotatab_file:mod_tls:mod_tls_shmcache:mod_ldap:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_facl:mod_dynmasq' '--sysconfdir=/etc' '--localstatedir=/run/proftpd' '--enable-ctrls' '--enable-ipv6' '--with-includes=/usr/include/mysql:/usr/include/postgresql' '--with-libraries=/usr/lib/mysql:/usr/lib/postgresql' '--enable-nls' '--enable-redis' '--enable-facl' '--with-systemd' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fcommon' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fcommon' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fcommon'

  CFLAGS: -g2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fcommon -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fcommon -rdynamic -L/usr/lib/postgresql -L/usr/lib/mysql -L/usr/lib/ -L/usr/lib
  LIBS: -lacl  -lssl -lcrypto -lsodium -lcap  -lpq  -lm -lmysqlclient -lz  -lldap -llber  -lssl  -lpam  -lcrypto -lsupp -lattr -lcrypt -ldl -lhiredis  -pthread

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (OpenSSL 1.1.1g  21 Apr 2020)
    - PCRE support
    + POSIX ACL support
    + Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

```
[root@mysystem ~]# cat /etc/proftpd/proftpd.conf
# ProFTPD configuration file
# ===============================================================

# Basic stuff
ServerName                  "My FTP server"
ServerAdmin                 "root@my.domain"
ServerType                  standalone
DefaultServer               on

# Host on a custom port
# See also PassivePorts
Port                        14000

# Enable IPv6
UseIPv6                     on

# To prevent DoS attacks, set the maximum number of child processes
# to 30.  If you need to allow more than 30 concurrent connections
# at once, simply increase this value.  Note that this ONLY works
# in standalone mode, in inetd mode you should use an inetd server
# that allows you to limit maximum number of processes per service
# (such as xinetd).
MaxInstances                30

# Timing attack mitigation with mod_delay
DelayEngine                 on
DelayTable                  /var/proftpd/proftpd.delay

# Enable ACL support if the respective module is available
<IfModule mod_facl.c>
    FACLEngine                  on
</IfModule>

# Dynamic IP address handling
# Periodically fetch a new external IP address from the DNS
# name specified at MasqueradeAddress
<IfModule mod_dynmasq.c>
    # Fetch a new IP address every 10 minutes
    DynMasqRefresh              600
</IfModule>

# Server-level TLS configuration
# Requires mod_tls_shmcache
TLSSessionCache             shm:/file=/tmp/proftpd/sess_cache
TLSStaplingCache            shm:/file=/tmp/proftpd/ocsp_cache

<Global>
    User                        proftpd
    Group                       proftpd
    DefaultRoot                 /data/ftp/share
    
    # Connection-related settings
    PassivePorts                14001 14059
    # NAT handling
    MasqueradeAddress           my.domain
        
    MaxClients                  20
    
    # Global file access/transmission tweaks
    AllowOverwrite              on
    DefaultTransferMode         binary
    
    # Lockdown and obfuscation
    DirFakeGroup                on
    DirFakeUser                 on
    DirFakeMode                 770
    ServerIdent                 off
    ShowSymlinks                off
    
    # Logging
    # Do not write an xferlog, so that we do not need to
    # use logrotate
    TransferLog                 none
    # Restrict other logging to important stuff
    SyslogLevel                 warn
    
    # FTPS/TLS configuration
    TLSEngine                   on
    TLSRequired                 on
    TLSOptions                  UseImplicitSSL NoSessionReuseRequired
    TLSRSACertificateFile       /data/letsencrypt/certbot/config/live/my.domain/fullchain.pem
    TLSRSACertificateKeyFile    /data/letsencrypt/certbot/config/live/my.domain/privkey.pem
    TLSDHParamFile              /etc/proftpd/ffdhe2048.txt
    TLSProtocol                 ALL -SSLv3 -TLSv1 -TLSv1.1
    TLSCipherSuite              ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    TLSServerCipherPreference   off
    TLSSessionTickets           off
    # 2020-06-19 OCSP stapling does not appear to work with ProFTPD 1.3.6c and FileZilla 3.46.3
    #TLSStapling                    on
    
    # User access settings
    # Only allow members of group(s) ftp,othergroup
    <Limit LOGIN>
        AllowGroup              OR ftp
    </Limit>
    # Always deny any kind of file or directory access
    # for "other", i.e. prevent world-readable and world-
    # writable files and directories
    Umask                       007
    # Bar use of SITE CHMOD by default
    <Limit SITE_CHMOD>
        DenyAll
    </Limit>
    # Hide stuff from the users that they cannot access
    # If ACLs are used to control user access, then for
    # HideNoAccess to work properly the module
    # "mod_facl.c" must be available and its
    # server-config-level directive "FACLEngine" must
    # be set to "on"
    <IfModule mod_facl.c>
        <Directory /data/ftp/share>
            HideNoAccess                on
        </Directory>
        # Do not allow any operations on items that are
        # hidden by the HideNoAccess directive
        <Limit DIRS>
            IgnoreHidden                on
        </Limit>
    </IfModule>
    
</Global>
```

```
[root@mysystem ~]# cat /etc/proftpd/ffdhe2048.txt 
-----BEGIN DH PARAMETERS-----
MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
+8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
-----END DH PARAMETERS-----
```

**Comment by Castaglia** [comment]
I believe this might be the same as Issue #1027 .  Can you try the latest code from the master branch, to confirm?

**Comment by eomanis** [comment]
> I believe this might be the same as Issue #1027 . Can you try the latest code from the master branch, to confirm?

You are likely right, as the master branch does not exhibit this bug and appears to work as expected.
