### ISSUE TITLE
SFTP Too many bad authentication attempts - Terminal is working

### ISSUE THREAD

**Issue by phhoef** [proftpd/proftpd#1771]
### What I Did

I've created a new connection to a customer's SFTP server.
So I do not know what configuration they are using.

When trying to connect, I see the following error.
<img width="294" alt="SCR-20240110-mfqq" src="https://github.com/proftpd/proftpd/assets/32458104/0ef25719-55d0-4b99-a367-acd484b4dbcd">

In the logs, I see this.
```
2024-01-10 13:38:05,358 [sshj-Reader-files.api.lhgroup.de/20.73.215.252:3122-1704890284650] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Too many bad authentication attempts!
net.schmizz.sshj.transport.TransportException: Too many bad authentication attempts!
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:543) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:499) [sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) [sshj-0.35.0.jar:?]
2024-01-10 13:38:05,366 [Thread-43] ERROR net.schmizz.concurrent.Promise - <<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: Too many bad authentication attempts!
2024-01-10 13:38:06,159 [sshj-Reader-files.api.lhgroup.de/20.73.215.252:3122-1704890285492] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Too many bad authentication attempts!
net.schmizz.sshj.transport.TransportException: Too many bad authentication attempts!
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:543) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:499) [sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) [sshj-0.35.0.jar:?]
2024-01-10 13:38:06,161 [Thread-43] ERROR net.schmizz.concurrent.Promise - <<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: Too many bad authentication attempts!

```

This is my configuration
<img width="522" alt="SCR-20240110-mgav" src="https://github.com/proftpd/proftpd/assets/32458104/2d064bea-3e70-4cef-a7f2-ef3968b5f535">

### What I Expected/Wanted

I would have expected, that I can establish the connection.
When trying to connect to the very same server via command line, it is working.
```bash
sftp -i ~/.ssh/key.pem -P 3122 -vvv user@files.api.XXX.de
```

**Comment by Castaglia** [comment]
Where you able to determine what the issue was?  I ask for the sake of other folks, who might be searching (and find this ticket) for similar issues.  Thanks!

**Comment by phhoef** [comment]
Sorry, I noticed that I was accidentally posting this issue here. I even don't know if proftpd is used.
I think the problem is related to Cyberduck and I mixed up the Github repos .. - sorry

**Comment by Castaglia** [comment]
No worries.  Thanks for the follow-up.
