### ISSUE TITLE
pool_destroy_pool_test -- Test timeout expired

### ISSUE THREAD

**Issue by Sashan** [proftpd/proftpd#711]
### What I Did
`pool_destroy_pool_test` unit test always fails with `Test timeout expired` error on Oracle Solaris.

### ProFTPD Version and Configuration

I'm using 1.3.6
    $ proftpd -V

```Compile-time Settings:
  Version: 1.3.6 (stable)
  Platform: SOLARIS2 (SOLARIS2_11) [SunOS 5.11 i86pc]
  Built: Mon May 28 2018 14:27:18 UTC
  Built With:
    configure  '--prefix=/usr' '--mandir=/usr/share/man' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--libdir=/usr/lib/amd64' 'install_user=anedvedi' 'install_group=staff' '--sysconfdir=/etc' '--localstatedir=/var/run' '--libexecdir=/usr/lib/proftpd/amd64' '--enable-ipv6' '--enable-ctrls' '--enable-facl' '--enable-nls' '--enable-dso' '--enable-openssl' '--enable-tests' '--disable-static' '--with-modules=mod_solaris_audit:mod_solaris_priv' '--with-shared=mod_facl:mod_wrap:mod_tls:mod_tls-fips-140:mod_auth_gss:mod_gss' '--enable-buffer-size=16384' 'FIPS_CPPFLAGS=-I/usr/include/openssl/fips-140' 'FIPS_LDFLAGS=-R/lib/openssl/fips-140/64' 'CC=/opt/solarisstudio12.4/bin/cc' 'CFLAGS=-m64 -xO4 -xchip=generic -Ui386 -U__i386 -xregs=no%frameptr -mt -I/usr/include/kerberosv5 -DHAVE_KRB5_H=1 -DKRB5_DLLIMP= -DHAVE__GETGRPSBYMEMBER -D_SOLARIS_DTRACE -g -xO0' 'LDFLAGS=-m64 -z now -z guidance=nolazyload -z nolazyload -lbsm' 'CPPFLAGS=-m64' 'CXX=/opt/solarisstudio12.4/bin/CC' 'CXXFLAGS=-norunpath -m64 -xO4 -xchip=generic -Ui386 -U__i386 -xregs=no%frameptr'

  CFLAGS: -m64 -xO4 -xchip=generic -Ui386 -U__i386 -xregs=no%frameptr -mt -I/usr/include/kerberosv5 -DHAVE_KRB5_H=1 -DKRB5_DLLIMP= -DHAVE__GETGRPSBYMEMBER -D_SOLARIS_DTRACE -g -xO0
  LDFLAGS: -L$(top_srcdir)/lib -m64 -z now -z guidance=nolazyload -z nolazyload -lbsm 
  LIBS: -lsec -lintl  -lssl -lcrypto -lpam -lsupp 

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/run/proftpd.pid
    Scoreboard File:
      /var/run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd/amd64

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    - PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    - xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 16384
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 1024
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```
I did try to debug the issue. It has turned out the `pool_destroy_pool_test` actually passes.
The stack unwinds to libcheck and continues to run. As soon as I hit `CTRL+C` in gdb I interrupt
the program and see stack as follows:
```
#1  0x00007fffbf17436a in free () from /lib/64/libc.so.1
#2  0x00000000004871bf in pool_release_free_block_list () at pool.c:408
#3  0x0000000000487665 in free_pools () at pool.c:488
#4  0x0000000000503825 in tear_down () at api/pool.c:42
#5  0x00007fffbc109b3c in srunner_run_teardown () from /usr/lib/64/libcheck.so.0
#6  0x00007fffbc109e53 in tcase_run_tfun_nofork.isra () from /usr/lib/64/libcheck.so.0
#7  0x00007fffbc10a3ce in srunner_run_tagged () from /usr/lib/64/libcheck.so.0
#8  0x000000000062071b in main (argc=1, argv=0x7fffbffff668) at api/tests.c:142
```
I let program continue for a while and hit `CTRL+C` after few seconds. Just to see the stack remains
same. I did some stepping just to find out the program spins here:
```
401 static void pool_release_free_block_list(void) {
402   union block_hdr *blok = NULL, *next = NULL;
403 
404   pr_alarms_block();
405 
406   for (blok = block_freelist; blok; blok = next) {
407     next = blok->h.next;
408     free(blok);
409   }
410   block_freelist = NULL;
411 
412   pr_alarms_unblock();
413 }
```

stepping program with display on `next` I am seeing output as follows
```
(gdb) n
408         free(blok);
1: next = (union block_hdr *) 0x75b270
(gdb) 
409       }
1: next = (union block_hdr *) 0x75b270
(gdb) 
407         next = blok->h.next;
1: next = (union block_hdr *) 0x75b270
(gdb) 
408         free(blok);
1: next = (union block_hdr *) 0x75b4a0
(gdb) 
409       }
1: next = (union block_hdr *) 0x75b4a0
(gdb) 
407         next = blok->h.next;
1: next = (union block_hdr *) 0x75b4a0
(gdb) 
408         free(blok);
1: next = (union block_hdr *) 0x75b270
```
so there is a cycle in a list. And we are lucky the `pool_destroy_pool_test` can create error condition for us. I'll try to keep poking around and fix it.

**Comment by Castaglia** [comment]
It's been a long while on this issue; does it still occur for you?  I'm not able to reproduce this error locally, so I'm wondering what might be different.

**Comment by Sashan** [comment]
I'm not with Solaris any more. so can't tell. I think this can be closed.

**Comment by Castaglia** [comment]
> I'm not with Solaris any more. so can't tell. I think this can be closed.

No worries.  If and when someone else on Solaris encounters this issue, we can re-open this.  Thanks!
